//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shadowsocks.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shadowsocks.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 # translation for Simplified Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///Mode=系统代理模式
        ///No modify system proxy=保持当前状态不修改
        ///Disable system proxy=直连模式
        ///PAC=PAC 模式
        ///Global=全局模式
        ///Proxy rule=代理规则
        ///Bypass LAN=绕过局域网
        ///Bypass LAN &amp;&amp; China=绕过局域网和大陆
        ///Bypass LAN &amp;&amp; not China=绕过局域网和非大陆
        ///User custom=用户自定义
        ///Disable bypass=全局
        ///Servers=服务器
        ///Edit servers...=编辑服务器...
        ///Import servers from file...=从文件导入...
        ///Import from clipboard SSR links...=从剪贴板SSR链接导入...
        ///Import from screen QRCode...=从屏幕二维码导入...
        ///Servers Subscribe=服务器订阅
        ///Subscribe setting... [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string cn {
            get {
                return ResourceManager.GetString("cn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] libsscrypto_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] libsscrypto64_dll {
            get {
                object obj = ResourceManager.GetObject("libsscrypto64_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] mgwz_dll {
            get {
                object obj = ResourceManager.GetObject("mgwz_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ngnl {
            get {
                object obj = ResourceManager.GetObject("ngnl", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 listen-address __PRIVOXY_BIND_IP__:__PRIVOXY_BIND_PORT__
        ///show-on-task-bar 0
        ///activity-animation 0
        ///forward-socks5 / 127.0.0.1:__SOCKS_PORT__ .
        ///hide-console
        ///__BYPASS_ACTION__
        ///
        /// 的當地語系化字串。
        /// </summary>
        internal static string privoxy_conf {
            get {
                return ResourceManager.GetString("privoxy_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] privoxy_exe {
            get {
                object obj = ResourceManager.GetObject("privoxy_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] proxy_pac_txt {
            get {
                object obj = ResourceManager.GetObject("proxy_pac_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ss16 {
            get {
                object obj = ResourceManager.GetObject("ss16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ss20 {
            get {
                object obj = ResourceManager.GetObject("ss20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ss24 {
            get {
                object obj = ResourceManager.GetObject("ss24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap ssw128 {
            get {
                object obj = ResourceManager.GetObject("ssw128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 ! Put user rules line by line in this file.
        ///! See https://adblockplus.org/en/filter-cheatsheet
        /// 的當地語系化字串。
        /// </summary>
        internal static string user_rule {
            get {
                return ResourceManager.GetString("user_rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 # translation for Traditional Chinese
        ///
        ///Shadowsocks=Shadowsocks
        ///
        ///# Menu items
        ///
        ///Mode=系統代理模式
        ///No modify system proxy=保持當前狀態不修改
        ///Disable system proxy=直連模式
        ///PAC=PAC 模式
        ///Global=全局模式
        ///Proxy rule=代理規則
        ///Bypass LAN=繞過區域網路
        ///Bypass LAN &amp;&amp; China=繞過區域網路和大陸
        ///Bypass LAN &amp;&amp; not China=繞過區域網路和非大陸
        ///User custom=用戶自定義
        ///Disable bypass=全局
        ///Servers=伺服器
        ///Edit servers...=編輯伺服器...
        ///Import servers from file...=從文件導入...
        ///Import from clipboard SSR links...=从剪貼板SSR連結導入...
        ///Import from screen QRCode...=从熒幕 QR 碼導入...
        ///Servers Subscribe=伺服器訂閱
        ///Subscribe sett [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string zh_tw {
            get {
                return ResourceManager.GetString("zh_tw", resourceCulture);
            }
        }
    }
}
